#
# This is free software, license use GPL3.
#
# Copyright (c) 2020, Chuck <fanck0605@qq.com>
#

name: openwrt-lean

on:
  push:
    branches:
      - openwrt-lean
  schedule:
    - cron: '00 18 * * *'
  watch:
    types: [started]

jobs:

  build:

    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:

      - name: Checkout Project
        uses: actions/checkout@master
        with:
          ref: openwrt-lean

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker image prune -a -f
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler antlr3 gperf swig
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Show Large Files
        run: |
          root_files=$(ls / | grep -vE '^(proc|run|sys)$' | sed 's:^:/:')
          sudo -E du -ah $root_files | grep -E '^[0-9.]*?[GTPEZY]'

      - name: Initialize Source
        run: |
          git clone -b master https://github.com/coolsnowwolf/lede.git
          cd lede && git am ../patches/*.patch

      - name: Install Extra Packages
        run: |
          cd lede/package

          # upgrade argon theme
          rm -rf lean/luci-theme-argon
          git clone --depth 1 -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git lean/luci-theme-argon

          # install filebrowser
          svn co https://github.com/project-openwrt/openwrt/trunk/package/ctcgfw/filebrowser lean/filebrowser
          svn co https://github.com/project-openwrt/openwrt/trunk/package/ctcgfw/luci-app-filebrowser lean/luci-app-filebrowser

          # install luci for 0.91 oled
          git clone --depth 1 -b master https://github.com/NateLol/luci-app-oled.git lean/luci-app-oled

      - name: Install Feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Customize Config
        run: |
          cd lede
          cat ../config.seed > .config
          make defconfig

      - name: Build OpenWrt
        run: |
          cd lede
          make download -j8
          make -j$(nproc) || make -j1 V=s

      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt
          path: ./lede/bin/targets/rockchip/armv8
